// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedBadge.Data.Context;

#nullable disable

namespace RedBadge.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230303045120_NFLStuff")]
    partial class NFLStuff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedBadge.Data.Entities.AwayTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AwayTeams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Philadelphia Eagles"
                        });
                });

            modelBuilder.Entity("RedBadge.Data.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("AwayTeamScore")
                        .HasColumnType("int");

                    b.Property<int?>("AwayTeamVotes")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("HighlightLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTeamScore")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTeamVotes")
                        .HasColumnType("int");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayTeamId = 1,
                            AwayTeamScore = 35,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HighlightLink = "https://www.youtube.com/watch?v=BWkt79xkd00&ab_channel=NFL",
                            HomeTeamId = 1,
                            HomeTeamScore = 38,
                            LeagueName = "NFL"
                        });
                });

            modelBuilder.Entity("RedBadge.Data.Entities.HomeTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomeTeams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kansas City Chiefs"
                        });
                });

            modelBuilder.Entity("RedBadge.Data.Entities.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NFL"
                        },
                        new
                        {
                            Id = 2,
                            Name = "NBA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MLB"
                        },
                        new
                        {
                            Id = 4,
                            Name = "NHL"
                        });
                });

            modelBuilder.Entity("RedBadge.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Championships")
                        .HasColumnType("int");

                    b.Property<int?>("Fans")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Championships = 2,
                            Name = "Patrick Mahomes",
                            TeamId = 16
                        },
                        new
                        {
                            Id = 2,
                            Championships = 0,
                            Name = "Justin Jefferson",
                            TeamId = 21
                        },
                        new
                        {
                            Id = 3,
                            Championships = 0,
                            Name = "Joe Burrow",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 4,
                            Championships = 0,
                            Name = "Josh Allen",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 5,
                            Championships = 0,
                            Name = "Jalen Hurts",
                            TeamId = 26
                        });
                });

            modelBuilder.Entity("RedBadge.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Championships")
                        .HasColumnType("int");

                    b.Property<int?>("Fans")
                        .HasColumnType("int");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int?>("Loses")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Championships = 2,
                            LeagueId = 1,
                            Loses = 13,
                            Name = "Arizona Cardinals",
                            Wins = 4
                        },
                        new
                        {
                            Id = 2,
                            Championships = 0,
                            LeagueId = 1,
                            Loses = 10,
                            Name = "Atlanta Falcons",
                            Wins = 7
                        },
                        new
                        {
                            Id = 3,
                            Championships = 2,
                            LeagueId = 1,
                            Loses = 7,
                            Name = "Baltimore Ravens",
                            Wins = 10
                        },
                        new
                        {
                            Id = 4,
                            Championships = 2,
                            LeagueId = 1,
                            Loses = 3,
                            Name = "Buffalo Bills",
                            Wins = 13
                        },
                        new
                        {
                            Id = 5,
                            Championships = 0,
                            LeagueId = 1,
                            Loses = 10,
                            Name = "Carolina Panthers",
                            Wins = 7
                        },
                        new
                        {
                            Id = 6,
                            Championships = 9,
                            LeagueId = 1,
                            Loses = 14,
                            Name = "Chicago Bears",
                            Wins = 3
                        },
                        new
                        {
                            Id = 7,
                            Championships = 0,
                            LeagueId = 1,
                            Loses = 4,
                            Name = "Cincinnati Bengals",
                            Wins = 12
                        },
                        new
                        {
                            Id = 8,
                            Championships = 8,
                            LeagueId = 1,
                            Loses = 10,
                            Name = "Cleveland Browns",
                            Wins = 7
                        },
                        new
                        {
                            Id = 9,
                            Championships = 5,
                            LeagueId = 1,
                            Loses = 5,
                            Name = "Dallas Cowboys",
                            Wins = 12
                        },
                        new
                        {
                            Id = 10,
                            Championships = 3,
                            LeagueId = 1,
                            Loses = 12,
                            Name = "Denver Broncos",
                            Wins = 5
                        },
                        new
                        {
                            Id = 11,
                            Championships = 4,
                            LeagueId = 1,
                            Loses = 8,
                            Name = "Detroit Lions",
                            Wins = 9
                        },
                        new
                        {
                            Id = 12,
                            Championships = 13,
                            LeagueId = 1,
                            Loses = 9,
                            Name = "Green Bay Packers",
                            Wins = 8
                        },
                        new
                        {
                            Id = 13,
                            Championships = 0,
                            LeagueId = 1,
                            Loses = 13,
                            Name = "Houston Texans",
                            Wins = 3
                        },
                        new
                        {
                            Id = 14,
                            Championships = 4,
                            LeagueId = 1,
                            Loses = 12,
                            Name = "Indianapolis Colts",
                            Wins = 4
                        },
                        new
                        {
                            Id = 15,
                            Championships = 0,
                            LeagueId = 1,
                            Loses = 8,
                            Name = "Jacksonville Jaguars",
                            Wins = 9
                        },
                        new
                        {
                            Id = 16,
                            Championships = 4,
                            LeagueId = 1,
                            Loses = 3,
                            Name = "Kansas City Chiefs",
                            Wins = 14
                        },
                        new
                        {
                            Id = 17,
                            Championships = 3,
                            LeagueId = 1,
                            Loses = 11,
                            Name = "Las Vegas Raiders",
                            Wins = 6
                        },
                        new
                        {
                            Id = 18,
                            Championships = 1,
                            LeagueId = 1,
                            Loses = 7,
                            Name = "Los Angeles Chargers",
                            Wins = 10
                        },
                        new
                        {
                            Id = 19,
                            Championships = 4,
                            LeagueId = 1,
                            Loses = 12,
                            Name = "Los Angeles Rams",
                            Wins = 5
                        },
                        new
                        {
                            Id = 20,
                            Championships = 2,
                            LeagueId = 1,
                            Loses = 8,
                            Name = "Miami Dolphins",
                            Wins = 9
                        },
                        new
                        {
                            Id = 21,
                            Championships = 0,
                            LeagueId = 1,
                            Loses = 4,
                            Name = "Minnesota Vikings",
                            Wins = 13
                        },
                        new
                        {
                            Id = 22,
                            Championships = 6,
                            LeagueId = 1,
                            Loses = 9,
                            Name = "New England Patriots",
                            Wins = 8
                        },
                        new
                        {
                            Id = 23,
                            Championships = 1,
                            LeagueId = 1,
                            Loses = 10,
                            Name = "New Orleans Saints",
                            Wins = 7
                        },
                        new
                        {
                            Id = 24,
                            Championships = 8,
                            LeagueId = 1,
                            Loses = 7,
                            Name = "New York Giants",
                            Wins = 9
                        },
                        new
                        {
                            Id = 25,
                            Championships = 1,
                            LeagueId = 1,
                            Loses = 10,
                            Name = "New York Jets",
                            Wins = 7
                        },
                        new
                        {
                            Id = 26,
                            Championships = 4,
                            LeagueId = 1,
                            Loses = 3,
                            Name = "Philadelphia Eagles",
                            Wins = 14
                        },
                        new
                        {
                            Id = 27,
                            Championships = 6,
                            LeagueId = 1,
                            Loses = 8,
                            Name = "Pittsburgh Steelers",
                            Wins = 9
                        },
                        new
                        {
                            Id = 28,
                            Championships = 5,
                            LeagueId = 1,
                            Loses = 4,
                            Name = "San Francisco 49ers",
                            Wins = 13
                        },
                        new
                        {
                            Id = 29,
                            Championships = 1,
                            LeagueId = 1,
                            Loses = 8,
                            Name = "Seattle Seahawks",
                            Wins = 9
                        },
                        new
                        {
                            Id = 30,
                            Championships = 2,
                            LeagueId = 1,
                            Loses = 9,
                            Name = "Tampa Bay Buccaneers",
                            Wins = 8
                        },
                        new
                        {
                            Id = 31,
                            Championships = 2,
                            LeagueId = 1,
                            Loses = 10,
                            Name = "Tennessee Titans",
                            Wins = 7
                        },
                        new
                        {
                            Id = 32,
                            Championships = 5,
                            LeagueId = 1,
                            Loses = 8,
                            Name = "Washington Commanders",
                            Wins = 8
                        });
                });

            modelBuilder.Entity("RedBadge.Data.Entities.Game", b =>
                {
                    b.HasOne("RedBadge.Data.Entities.AwayTeam", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedBadge.Data.Entities.HomeTeam", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("RedBadge.Data.Entities.Player", b =>
                {
                    b.HasOne("RedBadge.Data.Entities.Team", "Team")
                        .WithMany("PlayerNames")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("RedBadge.Data.Entities.Team", b =>
                {
                    b.HasOne("RedBadge.Data.Entities.League", "League")
                        .WithMany("TeamNames")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("RedBadge.Data.Entities.League", b =>
                {
                    b.Navigation("TeamNames");
                });

            modelBuilder.Entity("RedBadge.Data.Entities.Team", b =>
                {
                    b.Navigation("PlayerNames");
                });
#pragma warning restore 612, 618
        }
    }
}
